/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'agoenka' at '6/18/16 12:47 PM' with Gradle 2.14
 *
 * @author agoenka, @date 6/18/16 12:47 PM
 */
class Library {
    boolean someLibraryMethod() {
        println("Hey I am in a new line in Library Groovy File")
        true
    }
}