/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'agoenka' at '6/18/16 12:47 PM' with Gradle 2.14
 *
 * @author agoenka, @date 6/18/16 12:47 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
